export { default as Account } from "./Account";
export { default as Calls } from "./Calls";
export { default as Camera} from "./Camera";
export { default as Contacts} from "./Contacts";
export { default as GalleryPic} from "./GalleryPic";
export { default as InviteFriends} from "./InviteFriends";
export { default as NewGroup} from "./NewGroup";
export { default as PeopleNearby} from "./PeopleNearby";
export { default as SavedMessages} from "./SavedMessages";
export { default as Search} from "./Search";
export { default as Settings} from "./Settings";
export { default as TalktimeFeatures} from "./TalktimeFeatures";